// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/_sanity/fetch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/@nuxtjs/sanity/dist/runtime/server/routes/proxy').default>>>>
    }
    '/preview/enable': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/@nuxtjs/sanity/dist/runtime/server/routes/preview/enable').default>>>>
    }
    '/preview/disable': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/@nuxtjs/sanity/dist/runtime/server/routes/preview/disable').default>>>>
    }
  }
}
export {}